import type { Metadata } from "next";
import { Poppins, Montserrat, Yrsa } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: "100"
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const yrsa = Yrsa({
  subsets: ["latin"],
  variable: "--font-yrsa",
});

const metadata: Metadata = {
  title: "Ifha & Jefri",
  description: "Generated by @fit.tra_",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${montserrat.variable} ${yrsa.variable}`}>
        {children}
      </body>
    </html>
  );
}
