import { AnimationProvider } from "@/components/animations/AnimationProvider";
import { MusicProvider } from "@/components/music/MusicProvider";
import { amalfi, ivyMode } from "@/utils/fonts";
import type { Metadata } from "next";
import { Cinzel_Decorative, Poppins, Roboto } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: "400",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

const cinzel = Cinzel_Decorative({
  subsets: ["latin"],
  variable: "--font-cinzel",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Ifha & Jefri",
  description: "Generated by @fit.tra_",
  openGraph: {
    images: [
      {
        url: "https://wedding-invitation-ifha-jefri.vercel.app/images/cover-1.webp",
        secureUrl: "https://wedding-invitation-ifha-jefri.vercel.app/images/cover-1.webp",
        width: 1200,
        height: 630,
        alt: "Undangan Pernikahan Ifha & Jefri",
      },
    ],
  },

  alternates: {
    canonical: "https://wedding-invitation-ifha-jefri.vercel.app/",
  },

  applicationName: "Website Undangan Pernikahan Ifha dan Jefri Secara Online",

  icons: {
    icon: "https://wedding-invitation-ifha-jefri.vercel.app/assets/favicon.ico",
    shortcut: "https://wedding-invitation-ifha-jefri.vercel.app/assets/favicon.ico",
    apple: "https://wedding-invitation-ifha-jefri.vercel.app/assets/images/icon-192x192.png",
  },

  appleWebApp: {
    capable: true,
    title: "Website Undangan Pernikahan Ifha dan Jefri Secara Online",
    statusBarStyle: "black-translucent",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${poppins.variable}
          ${ivyMode.variable}
          ${amalfi.variable}
          ${roboto.variable}
          ${cinzel.variable}
          antialiased
        `}
      >
        <MusicProvider>
          <AnimationProvider>{children}</AnimationProvider>
        </MusicProvider>
      </body>
    </html>
  );
}
