import type { Metadata } from "next";
import { Poppins, Montserrat, Yrsa, Roboto, Cinzel_Decorative } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: "400",
});

const yrsa = Yrsa({
  subsets: ["latin"],
  variable: "--font-yrsa",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

const cinzel = Cinzel_Decorative({
  subsets: ["latin"],
  variable: "--font-cinzel",
  weight: "400"
});

const metadata: Metadata = {
  title: "Ifha & Jefri",
  description: "Generated by @fit.tra_",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${yrsa.variable} ${roboto.variable} ${cinzel.variable}`}>
        {children}
      </body>
    </html>
  );
}
